### ISSUE TITLE
US Refactoring/Components

### ISSUE THREAD

**Issue by MathiSans** [MathiSans/mood-diary#10]
## User Story
Refactoring/Components

## Description

<img width="405" alt="US_Description_1" src="https://github.com/MathiSans/mood-diary/assets/148532969/48a233ff-fb98-4493-b058-7e85b0dc1b0a">

## Value Proposition:

As a developer
I want to refactor the code to accommodate styled components
so that I can reuse them across the app's code

## Acceptance Criteria:

- [ ] the `tracking.js` is refactored to accommodate components and utils
- [ ] each component sits inside the `components` folder
- [ ] components sit inside their equally named folder
- [ ] as well as the component.styled files
- [ ] util functions sit inside the `utils` folder
- [ ] the code in `tracking.js` gets all components imported, necessary to return a complete and styled form
- [ ] the code in `tracking.js` gets all utils imported, necessary to make the form functional

## Tasks:

- [ ] create `components` folder
- [ ] create folder for each component
- [ ] create file for each component
- [ ] create file for each component.styles
- [ ] create `utils` folder
- [ ] refactor the code inside `tracking.js` to create separate components/utils

**Comment by MerleMak** [comment]
Usually when you get a review on one of your PRs, you don't need to write another user story for it :)
In this case you are already done, so its fine, but in the future, when you receive feedback on a PR, just make the changes push to the same branch as the PR was originally on and tag the reviewer to approve the new changes.

Happy hacking :))
