### ISSUE TITLE
User Story: Tag Cloud

### ISSUE THREAD

**Issue by MathiSans** [MathiSans/mood-diary#5]
## Value proposition
**As a** user
**I want to** to see a selection of tags
**In order to** I can quickly input my current mood

## Acceptance criteria
- user can see a selection of experiences and responses in tag clouds
- the "response"-tag cloud can be extended to see all available responses
- the selected tags are visually active

## Tasks
- [ ] create a data.js with an array of objects
- [ ] the objects include an identification key=value ("experience: fear") for each experience and all tags (responses) associated with the experience
- [ ] create an array with the "response"-tags
- [ ] the selected experience determines which "response"-tag cloud will be prominently displayed (if...then)
- [ ] a button to enable all available "response"-tags

**Comment by MerleMak** [comment]
Just a question:
So on submit of the form this Object structure will be saved?

You probably have one state where all the moods including the possible responses are listed.
You should then also create a "currentuser" Localstorage-state where the selected moods and responses are listed. 

I think you probably mean this already, maybe you can specifiy a little bit when (on submit probably) the objects are created :)

**Comment by MathiSans** [comment]
@MerleMak 

The example "array/object strucutre" is meant to be a example for the database array. Each object is a tag cloud option. Depending on which options/parameters the user selects a new object is being created and placed inside another array (array with user entries). Does that answer your question? :)

**Comment by MerleMak** [comment]
perfect :)
