### ISSUE TITLE
User Story: Welcome Page

### ISSUE THREAD

**Issue by MathiSans** [MathiSans/mood-diary#6]
##Value Proposition:

**As a** user 
**I want to** be welcomed and calmed down when entering the app
**so I can** feel engaged and connected to the product

##Description

##Acceptance Criteria:

- [ ] the user is welcomed with a small animation that encourages you to calm down/focus

##Tasks:

- [ ] research an engaging and quick onboarding (animation) that supports focus
- [ ] create an animation with (...)
- [ ] draft an onboarding and welcome text
- [ ] compose it together to a component in Next.js
- [ ] a skip button

**Comment by MerleMak** [comment]
Nice! 
Approved ✅
